server:
  port: 8888


spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 47.104.241.237:8848
    gateway:
      discovery:
        locator:
          #开启网关拉取nacos的服务
          enabled: true
          lower-case-service-id: true
#      routes:
#      - id: order-service
#        uri: lb://order-service
#        order: 1
#        predicates:
#        - Query=source,a.*
#        - Path=/order-service/**
#        - Before=2020-11-04T18:00:00+08:00[Asia/Shanghai]
#        filter:
#        - StripPrefix=1	 #去掉第一层前缀
#      - id: video-service
#        uri: lb://video-service
#        order: 1
#        predicates:
#        - Path=/video-service/**
#        filter:
#        - StripPrefix=1
